version: '3'

networks:
  zupMGMNetwork:

services:
  docker-postgres:
    image: postgres:10.4
    ports:
      - "5432:5432"
    container_name: docker-postgres
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - zupMGMNetwork
    restart: always
